version: '3.1'
services:
    server:
        # image: ubuntu:20.04
        build: ./docker
        stdin_open: true
        ports:
            - 80:80
        volumes:
          - ./src/:/var/www/html/
        depends_on:
         - db
    db:
        #platform: linux/x86_64 # - uncomment this line for mac os
        command: --default-authentication-plugin=mysql_native_password
        image: 'mysql:8.0'
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: SOME_ROOT_PASSWORD
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: no
        volumes:
            - ./docker/db/:/var/lib/mysql
            - ./docker/db_conf/my.conf:/etc/mysql/my.conf

    adminer:
        image: adminer
        restart: always
        depends_on:
         - db
        ports:
            - 8081:8080
