version: '3.1'
services:
    server:
        # image: ubuntu:20.04
        build: ./docker
        stdin_open: true
        ports:
            - 80:80
        volumes:
          - ./src/:/var/www/html/
        depends_on:
         - mysql
    mysql:
        command: --default-authentication-plugin=mysql_native_password
        image: 'mysql:8.0'
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ROOT_USER: '${DB_USERNAME}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            mysql_native_password: true
        volumes:
            - ./docker/db/:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
